blog/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('blog.apps.show.views',
    url(r'^$', 'index', name='show_index'),
    url(r'^blog/(?P<blog_id>\d+)$', 
        'show_blog', name='show_blog'),
    url(r'^blog/tags/(?P<tag_str>\S+)$', 
        'about_tag_blogs', name='about_tag_blogs'),

    url(r'^about$', 'about', name='about'),

    url(r'^post_article$', 
        'post_article', name='post_article'),
    url(r'^post_comment$', 
        'post_comment', name='post_comment'),
    url(r'^post_category$', 
        'post_category', name='post_category'),
)

urlpatterns += patterns('',
    (r'^pyer/login/$', 
        'django.contrib.auth.views.login', 
        {'template_name': 'login.html'}),
    )

blog/apps/show/models.py
# -*- coding:utf-8 -*-

from django.db import models

class Tag(models.Model):
    """标签"""

    name = models.CharField('名字', max_length=20)

    def __unicode__(self):

        return self.name

class Category(models.Model):
    """文章分类"""

    name = models.CharField('名字', 
        max_length=20, unique=True)

    def __unicode__(self):

        return self.name

class Article(models.Model):
    """博文"""

    title = models.CharField('标题', 
        max_length=80, unique=True,)
    content = models.TextField('内容')
    category = models.ForeignKey(
        Category, verbose_name="分类")
    tags = models.ManyToManyField(
        Tag, verbose_name='标签', 
        null=True, blank=True)

    readtimes = models.IntegerField('阅读次数', 
        default=1, null=True)
    instime = models.DateTimeField('插入时间', 
        auto_now_add=True)
    uptime = models.DateTimeField('更新时间', 
        auto_now=True)
    
    class Meta:

        ordering = ['-instime']
        
    def __unicode__(self):

        return self.title

    @property
    def pre_one(self):

        blog = Article.objects.filter(
            pk__lt=self.id).order_by('-pk')[0:1]

        return blog[0] if blog else None

    @property
    def later_one(self):

        blog = Article.objects.filter(
            pk__gt=self.id).order_by('pk')[0:1]
        
        return blog[0] if blog else None

    @property
    def get_comment_nums(self):

        return Comment.objects.filter(
            article=self).count()

class Comment(models.Model):
    """评论"""

    name = models.CharField('评论人', max_length=10)
    email = models.CharField('email', max_length=50)
    content = models.CharField('内容', max_length=200)
    instime = models.DateTimeField('插入时间', 
        auto_now_add=True)

    article = models.ForeignKey(
        Article, verbose_name="博文")

    class Meta:

        ordering = ['instime']

class FriendLink(models.Model):
    """友情链接"""

    name = models.CharField('内容', max_length=10)
    url = models.CharField('内容', max_length=50)
    weight = models.IntegerField('权重', default=1)

    class Meta:

        ordering = ['weight']

blog/apps/show/forms.py
#-*- coding: utf-8 -*-

import re

from django import forms

from models import Article, Category, Tag

class ArticleForm(forms.ModelForm):

    title = forms.CharField(label="标题",
        max_length=50,
        widget=forms.TextInput({'placeholder':'文章标题'}))
    category = forms.ModelChoiceField(label="分类",
        queryset=Category.objects.all(),
        widget=forms.Select({'class':'span2'}))
    tags = forms.CharField(label="标签",
        required=False,
        widget=forms.TextInput({'placeholder':'文章标签'}))
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={'style':"width:680px"}))

    def clean_tags(self):

        result= []
        tags = self.data.get('tags','').strip()
        for item in tags.split():
            tag = Tag.objects.get_or_create(
                name =  item
            )[0]
            result.append(tag)

        return result
   
    class Meta:
        model = Article
        exclude=('comments', 'readtimes')

class CategoryForm(forms.ModelForm):

    name = forms.CharField(label="名字",
        widget=forms.TextInput({'placeholder':'添加分类'}))

    class Meta:
        model = Category
        exclude=('articles')

blog/apps/show/views.py
# -*- coding:utf-8 -*-

import random
import datetime

from django.template import RequestContext
from django.http import HttpResponse, \
    Http404, HttpResponseRedirect
from django.shortcuts import render_to_response, \
    get_object_or_404
from django.db import transaction

from django.contrib.auth.decorators import login_required

from forms import ArticleForm, CategoryForm
from models import Article, Comment

def index(request):

    tags_clouds = {}

    blogs = Article.objects.all()
    for blog in blogs:
        for tag in blog.tags.all():
            tags_clouds.setdefault(tag.name, 1.0)
            tags_clouds[tag.name] += 1/20.0

    recent_comments = Comment.objects.all()[:5]
    arts = Article.objects.all()
    if arts.count()<=5:
        random_blog = arts
    else:
        random_blog = arts[random.randint(arts.count())-5:]

    return render_to_response('index.html',
        {"blogs":blogs,
         "tags_clouds": tags_clouds,
         "random_blog": random_blog,
         "recent_comments": recent_comments,},
        context_instance=RequestContext(request))

def show_blog(request, blog_id=0):
    
    blog = get_object_or_404(Article, pk=blog_id)
    comments = Comment.objects.filter(
        article__pk=blog.id)

    tags_clouds = {}

    blogs = Article.objects.all()
    for _blog in blogs:
        for tag in _blog.tags.all():
            tags_clouds.setdefault(tag.name, 1.0)
            tags_clouds[tag.name] += 1/20.0

    recent_comments = Comment.objects.all()[:5]
    arts = Article.objects.all()
    if arts.count()<=5:
        random_blog = arts
    else:
        random_blog = arts[random.randint(arts.count())-5:]

    return render_to_response('show_blog.html',
        {"blog":blog,
         "tags_clouds": tags_clouds,
         "random_blog": random_blog,
         "recent_comments": recent_comments,
         "comments": comments,},
        context_instance=RequestContext(request))

def about_tag_blogs(request, tag_str):

    blogs = []

    tags_clouds = {}

    _blogs = Article.objects.all()
    for _blog in _blogs:
        for tag in _blog.tags.all():
            tags_clouds.setdefault(tag.name, 1.0)
            tags_clouds[tag.name] += 1/20.0

    recent_comments = Comment.objects.all()[:5]
    arts = Article.objects.all()
    if arts.count()<=5:
        random_blog = arts
    else:
        random_blog = arts[random.randint(arts.count())-5:]

    for blog in Article.objects.all():
        for tag in blog.tags.select_related():
            if tag_str == tag.name.strip():
                blogs.append(blog)

    return render_to_response('about_tag_blog.html',
        {"blogs":blogs,
         "tag_str":tag_str,
         "tags_clouds": tags_clouds,
         "random_blog": random_blog,
         "recent_comments": recent_comments},
        context_instance=RequestContext(request))

@transaction.commit_on_success
def post_comment(request):

    user = request.POST.get('user')
    content = request.POST.get('content')
    email = request.POST.get('email')
    blog_id = request.POST.get('blog_id')
    quote = request.POST.get("quote", "").split("###")

    #过滤content里面的JS字符
    content = content.replace("<", "&lt;").replace(">", "&gt; ")

    blog = get_object_or_404(Article, pk=blog_id)
    if len(quote) == 3 and \
        Comment.objects.filter(pk=quote[2]):
        content = u"""
        <p>
        引用来自<code>%s楼-%s</code>的发言
        </p>""" % (quote[0], quote[1]) + content

    comment = Comment(
        article=blog,
        email=email,
        name=user, 
        content=content)
    comment.save()

    return HttpResponse("%d" % comment.id)

def about(request):

    return render_to_response('about.html',
        context_instance=RequestContext(request))

#########backend##########
@login_required
def post_article(request):

    form = ArticleForm()
    if request.method=='POST':

        form = ArticleForm(request.POST)
        print form.errors
        if form.is_valid():
            form.save()

            return HttpResponseRedirect('/')

    return render_to_response('post_article.html',
        {"form":form,},
        context_instance=RequestContext(request))

@login_required
def post_category(request):

    form = CategoryForm()
    if request.method=='POST':

        form = CategoryForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            return HttpResponse('''
            <script type="text/javascript">
                var cate = frameElement.api.opener.document.getElementById("id_category");
                cate.innerHTML = cate.innerHTML+"<option value='%s' selected='selected'>%s</option>";
                frameElement.api.close();
            </script>''' %(obj.id, obj.name))

    return render_to_response('post_category.html',
        {"form":form,},
        context_instance=RequestContext(request)) 

# def resetpwd(request):

#     from django.contrib.auth.models import User
#     u = User.objects.get(username__exact='hef')
#     u.set_password('lovemin5201314')
#     u.last_login = datetime.datetime.now()
#     u.date_joined = datetime.datetime.now()

#     u.save()

#     return HttpResponse('success')

blog/templates/about.html
{% extends 'base.html' %}

{% block container %}
  <div class="row" style="min-height:400px;">
    <div class="span12">
    <div class="page-header">
        <h1>About</h1>
    </div>
  
  
    <blockquote>
        <h5>Blog.Me</h5>
        <small>pythoner, unix</small>
        <small>rock, shutterbug</small>
        
        <br>
        <h5>Blog.Contact</h5>
      <small>
        <a href="mailto:flyoer@gmail.com">flyoer@gmail.com</a>
      </small>
      <small>
        <a href="http://weibo.com/flyoer">@篊飞飞</a>
      </small>
    </blockquote>
     
    </div>
  </div>
{% endblock %}

blog/templates/about_tag_blog.html
{% extends 'base.html' %}

{% block container %}
  <div class="row">
    <div class="span9">
        <div class="alert alert-info">
          跟标签<code>{{ tag_str }}</code>有关的文章如下
        </div>
        {% if blogs %}
        {% for blog in blogs %}
        
        <section style="margin-bottom:50px;">
        <h3><a href="{% url show_blog blog.id %}">{{ blog.title }}</a></h3>
        <p style="border-bottom:1px solid #ddd;padding-bottom:5px;"><span>{{ blog.uptime }}</span>
        | 标签:
        {% for tag in blog.tags.select_related %}
        <a href="/blog/tags/{{ tag.name }}" class="btn btn-mini btn-info">{{ tag.name }}
        </a>
        {% if forloop.last %}{% else %},{% endif %}
        {% endfor %}
        | 分类:<code>{{ blog.category.name }}</code>
        </p>
        {{ blog.content|safe }}
        <p style="text-align:right;">
        <span>
            <!-- <a class="btn btn-link btn-small">Views:(11)</a> -->
            <a class="btn btn-primary btn-mini disabled">评论: ( {{ blog.get_comment_nums }} )</a>
        </span>
        </p>
        </section>
        
        {% endfor %}
        {% else %}
        <div class="hero-unit" style="margin-top:20px;">
            <h2>博主删了文章去火星避难去了 Opps~~</h2>
            <a class="btn btn-info" href="/server">去火星追踪 »</a>
        </div>
        {% endif %}
    </div>
    {% include 'right_content.html' %}
  </div>
{% endblock %}

blog/templates/index.html
{% extends 'base.html' %}

{% block container %}
  <div class="row">
    <div class="span9">
    
        {% if blogs %}
        {% for blog in blogs %}
        
        <section style="margin-bottom:50px;">
        <h3><a href="{% url show_blog blog.id %}">{{ blog.title }}</a></h3>
        <p style="border-bottom:1px solid #ddd;padding-bottom:5px;"><span>{{ blog.uptime }}</span>
        | 标签:
        {% for tag in blog.tags.select_related %}
        <a href="/blog/tags/{{ tag.name }}" class="btn btn-mini btn-info">{{ tag.name }}
        </a>
        {% if forloop.last %}{% else %},{% endif %}
        {% endfor %}
        | 分类:<code>{{ blog.category.name }}</code>
        </p>
        {{ blog.content|safe }}
        <p style="text-align:right;">
        <span>
            <!-- <a class="btn btn-link btn-small">Views:(11)</a> -->
            <a class="btn btn-primary btn-mini disabled">评论: ( {{ blog.get_comment_nums }} )</a>
        </span>
        </p>
        </section>
        
        {% endfor %}
        {% else %}
        <div class="hero-unit" style="margin-top:20px;">
            <h2>博主删了文章去火星避难去了 Opps~~</h2>
            <a class="btn btn-info" href="/server">去火星追踪 »</a>
        </div>
        {% endif %}
    </div>
    {% include 'right_content.html' %}
  </div>
{% endblock %}

blog/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>登录 &middot; QieGao</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="python">
    <meta name="author" content="hef">

    <!-- Le styles -->
    <link href="http://images.wauee.com/bootstrap/2.21/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
      }

      .form-signin {
        max-width: 300px;
        padding: 19px 29px 29px;
        margin: 0 auto 20px;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
                border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
           -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
      }
      .form-signin .form-signin-heading,
      .form-signin .checkbox {
        margin-bottom: 10px;
      }
      .form-signin input[type="text"],
      .form-signin input[type="password"] {
        font-size: 16px;
        height: auto;
        margin-bottom: 15px;
        padding: 7px 9px;
      }

    </style>
    <link href="http://images.wauee.com/bootstrap/2.21/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <form class="form-signin" action="" method="post">
        <fieldset>
            <legend style="margin-bottom:5px;">Please sign in</legend>

        
        {% if form.errors %}
        <div class="alert alert-error" style="margin:0 auto;width:290px;padding:3px 5px;margin-bottom:8px;">
            <div style="padding-left:10px;">
            <span>你需要登陆才能访问上次的页面!</span>
            </div>
        </div>
        {% endif %}
        {% csrf_token %}
        

        {{ form.username }}
        {{ form.password }}
        <input type="hidden" name="next" value="/post_article" />
        <input class="btn btn-large btn-warning" id="submit" name="submit" type="submit" value="登录">
        </fieldset>
      </form>

    </div> <!-- /container -->
  </body>
</html>

blog/templates/post_article.html
{% extends 'base.html' %}

{% block js %}
<script type="text/javascript" src="http://images.wauee.com/zmv5/js/lhgdialog/lhgdialog.min.js"></script>
{% endblock %}


{% block container %}

<div class="page-header" style="margin-top:100px;">
    <h3 style="font-size:18px;">发表文章</h3>
</div>

    {% if form.errors %}
    <div class="alert alert-error">
      {{ form.errors }}  
    </div>
    {% endif %}

  <div class="row">
    <form class="form-horizontal" method="post" action="">
      <div class="control-group">
        <label class="control-label">
            {{ form.title.label }}
        </label>
        <div class="controls">
          {{ form.title }}
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">
            {{ form.category.label }}
        </label>
        <div class="controls">
          {{ form.category }}
          <a href="/post_category" class="btn btn-link tbox" title="添加分类" onclick="return showDialog(this);" w="360" h="140">添加</a>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label">
            {{ form.tags.label }}
        </label>
        <div class="controls">
          {{ form.tags }}
        </div>
      </div>
      
      <div class="control-group">
        <label class="control-label" for="inputPassword"></label>
        <div class="controls">
            {{ form.content }}
        </div>
      </div>
    
    <div class="form-actions">
        {% csrf_token %}
      <button type="submit" class="btn btn-primary">提交</button>
      <button type="button" class="btn">Cancel</button>
    </div>
    </form>
  </div>

<link href="http://a.tbcdn.cn/s/kissy/1.2.0/css/base-min.css" rel="stylesheet"/>
<link href="http://a.tbcdn.cn/s/kissy/1.2.0/editor/theme/cool/editor-pkg-min-datauri.css" rel="stylesheet"/>
<script src="http://a.tbcdn.cn/s/kissy/1.2.0/??kissy-min.js,uibase-min.js,component-min.js,dd-min.js,overlay-min.js,editor-min.js"></script>
<script src="http://a.tbcdn.cn/s/kissy/1.2.0/editor/biz/ext/editor-plugin-pkg-min.js"></script>
<script type="text/javascript">
KISSY.ready(function (S) {

    S.use('editor', function () {

        var KE = KISSY.Editor;
        var cfg = {
            attachForm:true,
            baseZIndex:10000,
            //自定义样式
            //customStyle:"p{color:purple;}",
            //自定义外部样式
            //customLink:["http://localhost/customLink.css","http://xx.com/y2.css"],
            //是否一开始自动聚焦
            //focus:true,
            pluginConfig:{
                "image":{
                    upload:{
                        serverUrl:"/image_upload",
                        surfix:"png,jpg,jpeg,gif",
                        fileInput:"Filedata",
                        sizeLimit:1000
                    }
                },
                "resize":{
                    direction:["y"]
                }
            }
        };
        var editor = KE("#id_content", S.clone(cfg)).use("elementpaths," +
            "sourcearea,preview," +
            "font,color,separator," +
            "justify,separator,link," +
            "image," +
            "smiley,separator,resize," +
            "separator,maximize");
    });
});
</script>
{% endblock %}

blog/templates/post_category.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>-Young-</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="python">
    <meta name="author" content="hef">

    <!-- Le styles -->
    <link href="http://images.wauee.com/bootstrap/2.21/css/bootstrap.min.css" rel="stylesheet">

    <link href="http://images.wauee.com/bootstrap/2.21/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
  </head>

  <body>
  <form class="form-horizontal" style="margin-top:30px;" action="" method="post">
    <div class="control-group">
      <div class="controls">
        {{ form.name }}
      </div>
    </div>
    <button type="submit" class="btn btn-info">提交</button>
      {% if form.errors %}
      <span>{{ form.name.errors.as_text }}</span>
      {% endif %}
    {% csrf_token %}
  </form>
  </body>
</html>

blog/templates/right_content.html
<div class="span3">
      <section>
        <iframe width="100%" height="550" class="share_self"  frameborder="0" scrolling="no" src="http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=550&fansRow=2&ptype=1&speed=0&skin=2&isTitle=0&noborder=1&isWeibo=1&isFans=0&uid=1684547443&verifier=e30813de&dpc=1"></iframe>
      </section>
    
      <section>
      <h5><i class="icon-comment"></i>&nbsp;最近评论</h5>
      <ul style="list-style:none;margin-left:3px;margin-bottom:0px;font-size:13px;">
      {% if recent_comments %}
      {% for comment in recent_comments %}
        <li>
          <a href="/blog/{{ comment.article.id }}#comment_tr_{{ comment.id }}">{{ comment.name }}:</a>
          <span>{{ comment.content|truncatechars:20 }}</span>
        </li>
      {% endfor %}
      {% else %}
        <li>
          <span>暂无评论~</span>
        </li>
      {% endif %}
      </ul>
      </section>
      
      <section style="font-size:13px;">
        <h5><i class="icon-leaf"></i>&nbsp;随机阅读</h5>
      <ul style="list-style:none;margin-left:3px;margin-bottom:0px;font-size:13px;">
        {% if random_blog %}
        {% for art in random_blog %}
        <li>
          <a href="/blog/{{ art.id }}">{{ art.title|truncatechars:20 }}</a>
        </li>
        {% endfor %}
        {% else %}
        <li>
          <span>暂无博文~</span>
        </li>
        {% endif %}
      </ul>
      </section>
      
      <section>
      <h5><i class="icon-tags"></i>&nbsp;标签云</h5>
      <div>
        {% if tags_clouds %}
        {% for tag_name, tag_count in tags_clouds.iteritems %}
        <a href="/blog/tags/{{ tag_name }}" class="badge badge-info" style="font-weight:normal;font-size:{{ tag_count }}em;">{{ tag_name }}</a>
        {% endfor %}
        {% else %}
        暂无可显示标签~
        {% endif %}
        </div>
      </section>
    </div>

blog/templates/show_blog.html
{% extends 'base.html' %}

{% block container %}
  <div class="row">
    <div class="span9">
    
        {% if blog %}
        <section style="margin-bottom:20px;">
        <h3><a href="javascript:void(0);">{{ blog.title }}</a></h3>
        <p style="border-bottom:1px solid #ddd;padding-bottom:5px;"><span>{{ blog.uptime }}</span>
        | 标签:
        {% for tag in blog.tags.select_related %}
        <a href="/blog/tags/{{ tag.name }}" class="btn btn-mini btn-info">{{ tag.name }}
        </a>
        {% if forloop.last %}{% else %},{% endif %}
        {% endfor %}
        | 分类:<code>{{ blog.category.name }}</code>
        </p>
        {{ blog.content|safe }}
        </section>
        <p style="width:100%;float:left;">
        
          {% if blog.pre_one %}
          <span class="pull-left" style="margin-left:30px;">
            <a href="/blog/{{ blog.pre_one.id }}">
            <i class="icon-arrow-left"></i>{{ blog.pre_one.title }}
            </a>
          </span>
          {% endif %}
          
          {% if blog.later_one %}
          <span class="pull-right"  style="margin-right:30px;">
          <a href="/blog/{{ blog.later_one.id }}">
            {{ blog.later_one.title }}<i class="icon-arrow-right"></i>
          </a>
          </span>
          {% endif %}
        </p>
        <div style="clear:both;"></div>
        <table class="table well" id="comment_table">
          <thead>
            <tr>
              <th colspan="3">评论</th>
            </tr>
          </thead>
          <tbody id="comment_tbody">
            {% if comments %}
            {% for comment in comments %}
            <tr id="comment_tr_{{ comment.id }}">
              <td width="20px">
                <span class="badge badge-info">{{ forloop.counter }}</span>
              </td>
              <td> 
                <span style="color:blue;font-weight:bold;">{{ comment.name }}</span> Post at:
                <code>{{ comment.instime }}</code>
              </td>
              <td width="30px;">
                <a href="javascript:void(0)" onclick="quote({{forloop.counter}}, '{{comment.name}}', {{comment.id}});">引用</a>
              </td>
            </tr>
            <tr>
              <td colspan="3" style="border-top:none;">
                <div style="padding-bottom:16px;padding-left:10px;">
                  {{ comment.content|safe }}
                </div>
              </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr id="commemt_null_td">
              <td colspan="3">
                <div style="padding-bottom:16px;padding-left:10px;">
                  暂无评论！
                </div>
              </td>
            </tr>
            {% endif %}
          </tbody>
        </table>
        
        <form class="form-horizontal" id="comment_form">
          <div class="control-group">
            <label class="control-label" style="width:70px;">姓名</label>
            <div class="controls" style="margin-left:90px;">
              <input type="text" id="id_name" placeholder="your name">
            </div>
          </div>
          <div class="control-group">
            <label class="control-label" style="width:70px;">Email</label>
            <div class="controls" style="margin-left:90px;">
              <input type="text" id="id_email" placeholder="email address">
              <span style="font-size:12px;" class="label label-info">可选项<span>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label" style="width:70px;"></label>
            <div class="controls" style="margin-left:90px;">
              <p id="quote_p" style="display:none;">引用来自<code id="quote_code"></code>的发言
                <a href="javascript:void(0);" onclick="cancelQuote();"><i class="icon-remove"></i></a>
              </p>
              <textarea id="id_content" style="width:440px;height:120px;"></textarea>
            </div>
          </div>
          <div class="control-group">
            <div class="controls" style="margin-left:90px;">
              <input type="hidden" name="quote_comment" value="" id="quote_comment"/>
              <input type="button" class="btn btn-primary" value="提交" id="post_comment_btn">
            </div>
          </div>
        </form>
        
        {% else %}
        <div class="hero-unit" style="margin-top:20px;">
            <h2>博主删了文章去火星避难去了 Opps~~</h2>
            <a class="btn btn-info" href="/server">去火星追踪 »</a>
        </div>
        {% endif %}
    </div>
    {% include 'right_content.html' %}
  </div>
<script type="text/javascript">
$("#post_comment_btn").click(function(){

    var comment_user = $.trim($("#id_name").val());
    var comment_email = $.trim($("#id_email").val());
    var comment_content = $.trim($("#id_content").val());
    var comment_tbody = $("#comment_tbody");
    var comment_quote = $("#quote_comment").val();

    var email_reg = /^([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\_|\.]?)*[a-zA-Z0-9]+\.[a-zA-Z]{2,3}$/;

    if(comment_user==''){
      alert('请填写名字.');
      $("#id_name").focus();
      return false;
    }

    if(comment_email!='' && !email_reg.test(comment_email)){
      alert('请填写正确的Email.');
      $("#id_email").focus();
      return false;
    }

    if(comment_content==''){
      alert('请填写评论内容.');
      $("#id_content").focus();
      return false;
    }

    $.ajax({
        type: "POST",
        url: "{% url post_comment %}",
        data: {
          "blog_id": {{ blog.id }}, 
          "user": comment_user,
          "email": comment_email,
          "quote": comment_quote,
          "csrfmiddlewaretoken": "{{ csrf_token }}",
          "content": comment_content },
        timeout: 2000,
        success: function(msg){
          location.reload();
        },
        error: function(msg){
          
        }
    });
});
function quote(lv, name, comment_id){
  $("#quote_comment").val(lv+"###"+name+"###"+comment_id);
  $("#id_content").focus();
  $("#quote_code").html(lv+"楼-"+name);
  $("#quote_p").fadeIn();
}
function cancelQuote(){
  $("#quote_comment").val('');
  $("#quote_p").fadeOut();
  return false;
}
</script>
{% endblock %}